version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 10
    rebase-strategy: "auto"
    target-branch: "master"
    labels:
      - "chores"
      - "dependencies"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "00:00"
      timezone: "UTC"
    allow:
      - dependency-type: "direct"
    commit-message:
      prefix: "Chores"
