name: Update dependencies

on:
  schedule:
    - cron: "00 23 * * 6"
  workflow_dispatch:

jobs:
  build:
    uses: userscripters/shared-actions/.github/workflows/workflow-update_dependencies.yml@master
